### PR TITLE
Optimise Imgix::Path#to_url by not generating the escaped query string twice

### PR DESCRIPTION
**Pull request by stevehodgkiss**
# Description

In profiling an application that renders a lot of Imgix images, I noticed a significant amount of time spent escaping the query string in `Imgix::Path#query`.

To generate a URL, `Imgix::Path#query` is called twice - once for the URL to be rendered, and again to generate the signature.

The change in this PR avoids generating the escaped query string twice, and almost doubles the performance of `to_url` on my machine.

Before:

```
❯ bundle exec ruby script/bench_to_url.rb
Warming up --------------------------------------
  Imgix::Path#to_url     1.683k i/100ms
Calculating -------------------------------------
  Imgix::Path#to_url     16.886k (± 0.6%) i/s -     85.833k in   5.083431s
```

After:

```
❯ bundle exec ruby script/bench_to_url.rb
Warming up --------------------------------------
  Imgix::Path#to_url     2.731k i/100ms
Calculating -------------------------------------
  Imgix::Path#to_url     27.278k (± 0.7%) i/s -    136.550k in   5.006213s
```

### CODE REVIEW

**Comment by frederickfogerty** [comment]
Hey there @stevehodgkiss thanks for the PR! I've pinged someone on our team with more extensive knowledge of this library than me to take a look at this, and hopefully we can get this merged in soon!

**Comment by ericdeansanchez** [comment]
@stevehodgkiss Nice! At a glance, I like this a lot. I'm currently working on performance improvements in our codebase and _deferring computation until it's needed_ is a technique I use often (it often helps to de-duplicate computation).

I will review this more thoroughly later today/tomorrow. Thanks for this!

**Review by sherwinski — APPROVED** [review]
Thanks for the PR @stevehodgkiss, this seems like a straightforward boost to me 👍

**Comment by sherwinski** [comment]
This branch is out of sync with `main` so I'm closing it in favor of #109 in order to unblock #108

**Pull request closed without merging**
