### PR TITLE
Move test dependecy to test group

### LINKED ISSUE #118: chore(test): more test dependencies to a separate group in Gemfile
Move test dependencies to a separate group in Gemfile

### PR DESCRIPTION
**Pull request by Jaskaran2**
## Description

In this PR the gems being used for the purpose of testing are moved to the test group in the gem file.

## Checklist

- [x] Read the [contributing guidelines](CONTRIBUTING.md).
- [x] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [x] All existing unit tests are still passing (if applicable).

### CODE REVIEW

**Comment by luqven** [comment]
Hey @Jaskaran2 , thanks for opening this PR!

This is a good start. But could you edit your commit message to match our [Contributing](https://github.com/imgix/imgix-rb/blob/main/CONTRIBUTING.md) guidelines regarding commit messages? 

If it's unclear or you need a hand just ping me and I'm happy to help.

**Comment by Jaskaran2** [comment]
> Hey @Jaskaran2 , thanks for opening this PR!
> 
> This is a good start. But could you edit your commit message to match our [Contributing](https://github.com/imgix/imgix-rb/blob/main/CONTRIBUTING.md) guidelines regarding commit messages?
> 
> If it's unclear or you need a hand just ping me and I'm happy to help.

Sure @luqven. I have made a change to commit message. Please let me know if its fine.

**Review by luqven — APPROVED** [review]
Hey @Jaskaran2, this looks great thanks for updating the commit message. I pulled this down locally and everything is working well. Our CI isn't configured for forks at the moment (my bad) so don't worry about the failing CI tests.

Thanks again for contributing!

ship-it

**Comment by Jaskaran2** [comment]
It was my pleasure @luqven . Please let me know if there is anything else I can help with

**Pull request merged**
