### PR TITLE
fix(travis-config): allow rbx-3.107 to fail

### PR DESCRIPTION
**Pull request by ericdeansanchez**
This PR makes failures allowable w.r.t. `rbx-3.107`. Prior to this PR the build
was failing due to `rbx-3.107`, now these failures are allowed while we
continue to troubleshoot the issue. Answers on how to correct these issues
were sparse and essentially all resulted in `allow_failures` being added to
the repos experiencing failures.

Right now, I think this issue is between travis and the gem vendor for rbx.

Below is information that could be helpful in the future:

Troubleshooting build failure:

```text
$ rvm use rbx-3.107 --install --binary --fuzzy
431 curl: (22) The requested URL returned error: 404 Not Found
432 Required rbx-3.107 is not installed - installing.
433 curl: (22) The requested URL returned error: 404 Not Found
434 Searching for binary rubies, this might take some time.
435 Requested binary installation but no rubies are available to download, consider skipping --binary flag.
436 Gemset '' does not exist, 'rvm rbx-3.107 do rvm gemset create ' first, or append '--create'.
437 The command "rvm use rbx-3.107 --install --binary --fuzzy" failed and exited with 2 during .
```

```text
13.43 $ rvm use rbx-3 --install --binary --fuzzy
432 curl: (22) The requested URL returned error: 404 Not Found
433 Required rbx-3 is not installed - installing.
434 curl: (22) The requested URL returned error: 404 Not Found
435 Searching for binary rubies, this might take some time.
436 Requested binary installation but no rubies are available to download, consider skipping --binary flag.
437 Gemset '' does not exist, 'rvm rbx-3 do rvm gemset create ' first, or append '--create'.
438 The command "rvm use rbx-3 --install --binary --fuzzy" failed and exited with 2 during .
439
440 Your build has been stopped.
```

[As of 2018, this was still seen as an issue](https://github.com/travis-ci/travis-ci/issues/5294). [Most travis](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/.travis.yml) configs I've seen just `allow_failures` for rbx.

**What even is rbx?**
>Rubinius is a ruby interpreter written in C++ using many advanced techniques and technologies such as LLVM, a "precise, compacting, generational garbage collector", a compatible C extension API to standard MRI Ruby, and many other awesome ideas that will give any language-nut a huge nerdon.

[Rbx](https://github.com/rubinius/rubinius/) itself seems to be either[ down or dead](https://rubinius.com)? Though, I don't think this is even rbx's fault as seen here:

```text
432 Required rbx-3.107 is not installed - installing.
433 curl: (22) The requested URL returned error: 404 Not Found
```

There could be an issue pulling/installing this on travis' end or some disconnect between travis and rbx? Or at least, the link provided on [**Travis**](https://docs.travis-ci.com/user/languages/ruby/) which is:

```text
https://rubies.travis-ci.org/rubinius
```

Just navigates to here:
Screen Shot 2020-06-05 at 9 52 45 AM

From @sherwinski:

>There could be an issue pulling/installing this on travis' end or some disconnect between travis and rbx?

To add a bit more context on this, from the Travis [community board](https://travis-ci.community/t/rvm-cannot-install-rbx-3-107/4998/2):

>We rely on the rubinius team to provide the binaries. When you make a request for rubinius, we ask our rubies.travis-ci.org 2 server for it. It then redirects to known location in the Rubinius team’s S3 bucket.

So it seems that the binaries are not available for Travis to pull in. And there's no way to say for sure if they ever will be again. I propose using allow_failures for the time being, and revisiting this again in the future.

### CODE REVIEW

**Comment by sherwinski** [comment]
> There could be an issue pulling/installing this on travis' end or some disconnect between travis and rbx?

To add a bit more context on this, from the Travis [community board](https://travis-ci.community/t/rvm-cannot-install-rbx-3-107/4998/2):

> We rely on the rubinius team to provide the binaries. When you make a request for rubinius, we ask our rubies.travis-ci.org 2 server for it. It then redirects to known location in the Rubinius team’s S3 bucket.

So it seems that the binaries are not available for Travis to pull in. And there's no way to say for sure if they ever will be again. I propose using `allow_failures` for the time being, and revisiting this again in the future.

**Review by sherwinski — COMMENTED** [review]
For the sake of comprehensibility, can we clean up the commit history on this branch a bit?

**Comment by ericdeansanchez** [comment]
Yeah, @sherwinski I originally had opened up a whole new branch, made the changes there with the intention of clean history. Though, I wondered if we we could squash all of these commits to try to be a bit more descriptive about what has already been attempted (to fix the problem).

I can easily clean this up and include more history (in a new branch, with a single commit), just lmk

**Review by sherwinski — APPROVED** [review]
Up to you, I don't mind keeping the history in this branch as reference, so long as we `Squash and merge` at the end. Either way, I would like the resulting history in the base branch to be succinct.

**Pull request merged**
