### PR TITLE
chore: add circleci config

### PR DESCRIPTION
**Pull request by frederickfogerty**
This PR adds CI config for CircleCI. The config is essentially the same as the Travis config, except that it doesn't include the Rubium config, since that didn't seem to work on Travis anyway.

### CODE REVIEW

**Comment by frederickfogerty** [comment]
Current dependencies on/for this PR:
* main
  * **PR #113**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by sherwinski — APPROVED** [review]
LGTM but just had two points for discussion:
1. Since migrating from travis isn't so 1-to-1, can we get some descriptive comments about all the newer pieces we're seeing in the circle config, e.g. everything in the `install-deps` and `steps` blocks. This would be helpful in the future if a different dev needs to figure their way around this.
2. Was there a specific motivation for checking in the lock file? I don't disagree with the choice but just wanted to be clear on the context as to why. CC @ericdeansanchez I remember discussing ruby lock files way back, can you confirm we're still good to check them into our libraries.

**Comment by frederickfogerty** [comment]
> * Since migrating from travis isn't so 1-to-1, can we get some descriptive comments about all the newer pieces we're seeing in the circle config, e.g. everything in the `install-deps` and `steps` blocks. This would be helpful in the future if a different dev needs to figure their way around this.

I agree that the `install-deps` command is confusing. Since it is simply just copied from the Ruby orb, I think it's best just to link that documentation, which I have done. I'll add some other comments to add any context I know of.

> * Was there a specific motivation for checking in the lock file? I don't disagree with the choice but just wanted to be clear on the context as to why. CC @ericdeansanchez I remember discussing ruby lock files way back, can you confirm we're still good to check them into our libraries.

It is recommended by Ruby/Rails to check-in the lockfile. If there was a clear decision in the past not do check it in, I'm happy to remove it again.

**Comment by frederickfogerty** [comment]
@sherwinski made some updates here, let me know what you think

**Comment by ericdeansanchez** [comment]
@frederickfogerty @sherwinski **the short answer: it's fine, check it in!** It's one of those things that people have opinions about.

The short story is there's been two popular opinions:
* check-in lock file for apps (reproducibility)
* do not check-in lock file for gems (flexibility for users)

But there's a third option: check-in the lock file and proactively (routinely) test against the newest version of dependencies.

I vote for this third option.

**Comment by ericdeansanchez** [comment]
We should add `.circleci` to the list of things we ignore when distributing this gem, e.g.

```
`git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features|.github|.circleci)/}) }
```

Mostly a comment: This dependency scan is wild lol. Here's the gems we use:
```
require "base64"
require "cgi/util"
require "erb"
require "digest"
require "net/http"
require "uri"
require "json"
```

**Comment by frederickfogerty** [comment]
Thanks for the feedback @ericdeansanchez. I think I'll remove the lockfile for now, and then we can add it when we add renovate or something else at a later stage.

**Review by sherwinski — APPROVED** [review]
LGTM 👍

**Pull request merged**
